/****************************************************************/
/* Auto generated by PGR for SEAL                               */
/*  (c) Copyright 2000 .MAD All rights reserved                 */
/*  http://pmad.forez.com/seal                                  */
/*                                                              */
/****************************************************************/
/*                                                              */
/*                          Filename.c                          */
/*                     (c) Copyright 2000                       */
/*                             Me                               */
/*                      All rights reserved                     */
/*                                                              */
/* Mail : me@mymail.com                                         */
/* Web  : http://www.myprovier.com/me/seal                      */
/*                                                              */
/* This file is a part of my program                            */
/* My program is ...                                            */
/*                                                              */
/****************************************************************/

#include"include\allegro.h"
#include"include\seal.h"
#include"include\app.h"
#include"include\button.h"
#include"include\menus.h"
#include"include\dialogs.h"
#include"include\iodlg.h"
#include"include\bcd.h"
#include"include\load_htm.h"
#include"include\desktop.h"

#define Msg_CloseBt        100001
#define Msg_SaveBt         100002
#define Msg_BrowseWall     100003


static p_button CloseBt = NULL;
static p_button SaveBt = NULL;
static p_history  AtTop = NULL;
static p_stattext Text1 = NULL; 
static p_textline WallPaper = NULL;
static p_stattext Text2 = NULL; 
static p_button BrowseWall = NULL;
static p_stattext Text3 = NULL; 
static p_history  WallStyle = NULL;

static l_long get_current_style_item ( void ) {

  l_text s = (l_text)getini_fromfile (INI_MAINFILE, INI_DESKTOP, "style");


  if ( s ) {

     if ( !stricmp(s, "(none)") )  return 0;
     if ( !stricmp(s, "stretch") ) return 1;
     if ( !stricmp(s, "center") )  return 2;

  };

  return 0;

};

static p_list get_img_items ( void ) {

  p_list p = list_init(_malloc(sizeof(t_list)), &free_filehistory_item, 0);

  if ( p ) {

     p->insert(p, new_filehistory_item("Jpeg files (*.jpg)", "*.jpg"));
     p->insert(p, new_filehistory_item("Gif files (*.gif)", "*.gif"));
     p->insert(p, new_filehistory_item("Bmp files (*.bmp)", "*.bmp"));
     p->insert(p, new_filehistory_item("Pcx files (*.pcx)", "*.pcx"));
     p->insert(p, new_filehistory_item("Tiff files (*.tif)", "*.tif"));
     p->insert(p, new_filehistory_item("Targa files (*.tga)", "*.tga"));
     p->insert(p, new_filehistory_item("Lbm files (*.lbm)", "*.lbm"));
     p->insert(p, new_filehistory_item("X Window Bitmap files (*.xbm)", "*.xbm"));
     p->insert(p, new_filehistory_item("Iax files (*.iax)", "*.iax"));
     p->insert(p, new_filehistory_item("Pse files (*.pse)", "*.pse"));
     p->insert(p, new_filehistory_item("Pixmap files (*.ppm)", "*.ppm"));
     p->insert(p, new_filehistory_item("Portable Greyscale-map files (*.pgm)", "*.pgm"));
     p->insert(p, new_filehistory_item("Vid files (*.vid)", "*.vid"));
     p->insert(p, new_filehistory_item("All files (*.*)", "*.*"));

  };


  return p;
};


static p_list MyVoid_AtTop ( void ) {

  p_list p = list_init(_malloc(sizeof(t_list)), &free_filehistory_item, 0);

  if ( p ) {

    p->insert(p, new_history_item("Bottom",NULL,0,NULL));
    p->insert(p, new_history_item("Top",NULL,0,NULL));

  };


  return p;
};





static p_list MyVoid_WallStyle ( void ) {

  p_list p = list_init(_malloc(sizeof(t_list)), &free_filehistory_item, 0);

  if ( p ) {

     p->insert(p, new_history_item("pattern", NULL, 0, NULL));
     p->insert(p, new_history_item("stretch", NULL, 0, NULL));
     p->insert(p, new_history_item("center", NULL, 0, NULL));

  };


  return p;
};

static void trans_ev ( p_object o, p_event event ) {

  if ( o->process == PH_PREPROCESS && event->type & EV_MESSAGE ) { /* I'm sorry to repeate this.... */
       switch ( event->message ) {
           case Msg_SaveBt : {

                l_int tb = (AtTop->current);
                t_event e = *event;

                mouse_set_cursor_focus_id (CUR_CLOCK);

                setini_tofile (INI_MAINFILE, INI_DESKTOP, "tool_bar", (char*)(&tb), INI_DECANUM);

                setini_tofile (INI_MAINFILE, INI_DESKTOP, "style", TEXTLINE(WallStyle)->text, INI_STRING);

                /* destroy current desktop wallpaper */
                if ( desktop->brush.state & BRUSH_SELFIMG )

                destroy_bitmap(desktop->brush.background);

                desktop->brush.background = NULL;

                /* convert style text to BRUSH_xxxx styles */
                switch ( WallStyle->current ) {

                   case 0 : desktop->brush.state &= ~(BRUSH_STRETCH|BRUSH_CENTER); break;
                   case 1 : desktop->brush.state |= BRUSH_STRETCH; break;
                   case 2 : desktop->brush.state |= BRUSH_CENTER; break;

                };

           if ( WallPaper->text )

              desktop->brush.background = load_image(WallPaper->text);

                desktop->brush.state |= BRUSH_SELFIMG;

                /* redraw only background of the desktop ( not redraw sub-views ) */
                desktop->draw_me(desktop);

                /* set ini data to file */
                setini_tofile (INI_MAINFILE, INI_DESKTOP, "wall_paper", WallPaper->text, INI_STRING);

            mouse_set_cursor_focus_id (CUR_ARROW);

               (*event) = e;
           }; break;

           case Msg_BrowseWall : {  
            /* If BrowseWall is clicked ... */
            
                 /* get choosed file */
                 l_text file = file_dialog(INI_TEXT("Browse"), INI_TEXT("Open"), "c:/", NULL, get_img_items() , FA_ALL, FL_OPEN, NULL);

                 if ( file )
                     /* set line to file */
                     WallPaper->set_text(WallPaper, file);

                 clear_event(event);

                 _free(file);
           }; break;
    };
  };



};

void Show_Win_ControlPanel () { /* Void to load window ControlPanel */
/* Declare the window's size in 'r' */
   t_rect   r = rect_assign(0, 0, 410, 180);

   l_long a = (l_long)getininum_fromfile (INI_MAINFILE, INI_DESKTOP, "tool_bar");

   /* Declare the window in 'ControlPanel' */
   p_appwin ControlPanel = appwin_init(_malloc(sizeof(t_appwin)),
                            r,
                            INI_TEXT("My SEAL - Control Panel"),
                            WF_MINIMIZE,
                            ap_id,
                            &trans_ev);

   /* Set window align */
   if ( ControlPanel ) VIEW(ControlPanel)->align |= TX_ALIGN_CENTER;

   /* Make and show the window */
   OBJECT(desktop)->insert(OBJECT(desktop), OBJECT(ControlPanel));

/* Declare the button's size in 'r' */
r = rect_assign(327, 140, 392, 165);

/* Declare the button in 'CloseBt' */
CloseBt = button_init(_malloc(sizeof(t_button)),
                      r,
                      INI_TEXT("Close"),
                      MSG_CLOSE,
                      BF_DEFAULT);

/* Add the button to the window declared in 'ControlPanel' */
OBJECT(ControlPanel)->insert(OBJECT(ControlPanel), OBJECT(CloseBt));



/* Declare the button's size in 'r' */
r = rect_assign(257, 140, 322, 165);

/* Declare the button in 'SaveBt' */
SaveBt = button_init(_malloc(sizeof(t_button)),
                      r,
                      INI_TEXT("Save"),
                      Msg_SaveBt,
                      BF_DEFAULT);

/* Add the button to the window declared in 'ControlPanel' */
OBJECT(ControlPanel)->insert(OBJECT(ControlPanel), OBJECT(SaveBt));



/* Declare the history's size in 'r' */
r = rect_assign(332, 30, 387, 50);

/* Declare the history in 'AtTop' */
 AtTop = history_init(_malloc(sizeof(t_history)),
                            r,
                            MyVoid_AtTop() ,
                            150,
                            HF_REWRITEUNABLE|LF_SELFLIST);



/* Add the history to the window declared in 'ControlPanel' */
OBJECT(ControlPanel)->insert(OBJECT(ControlPanel), OBJECT(AtTop));

if ( AtTop ) AtTop->rewrite_item(AtTop, a);

/* Declare the button's size in 'r' */
r = rect_assign(7, 30, 327, 50);

/* Declare the Stattext in 'Text1' */
     Text1 = stattext_init(_malloc(sizeof(t_stattext)),
                                r,
                                TX_ALIGN_BOTTOM,
                                INI_TEXT("Bar position (need to restart) :"));


/* Add the button to the window declared in 'ControlPanel' */
OBJECT(ControlPanel)->insert(OBJECT(ControlPanel), OBJECT(Text1));

/* Declare the button's size in 'r' */
r = rect_assign(7, 75, 327, 95);

/* Declare the textline in 'WallPaper' */
 WallPaper = textline_init(_malloc(sizeof(t_textline)),
                           r,
                           IO_DIR_LIMIT,
                           0);



/* Add the button to the window declared in 'ControlPanel' */
OBJECT(ControlPanel)->insert(OBJECT(ControlPanel), OBJECT(WallPaper));

      if ( WallPaper ) {

          l_text m = getini_fromfile (INI_MAINFILE, INI_DESKTOP, "wall_paper");

          WallPaper->set_text(WallPaper, m);

          _free(m);
      };

/* Declare the button's size in 'r' */
r = rect_assign(7, 55, 97, 75);

/* Declare the Stattext in 'Text2' */
     Text2 = stattext_init(_malloc(sizeof(t_stattext)),
                                r,
                                TX_ALIGN_BOTTOM,
                                INI_TEXT("WallPaper"));


/* Add the button to the window declared in 'ControlPanel' */
OBJECT(ControlPanel)->insert(OBJECT(ControlPanel), OBJECT(Text2));

/* Declare the button's size in 'r' */
r = rect_assign(332, 75, 387, 95);

/* Declare the button in 'BrowseWall' */
BrowseWall = button_init(_malloc(sizeof(t_button)),
                      r,
                      INI_TEXT("Browse"),
                      Msg_BrowseWall,
                      BF_DEFAULT);

/* Add the button to the window declared in 'ControlPanel' */
OBJECT(ControlPanel)->insert(OBJECT(ControlPanel), OBJECT(BrowseWall));


/* INI_TEXT("Browse") */

/* Declare the button's size in 'r' */
r = rect_assign(7, 100, 67, 120);

/* Declare the Stattext in 'Text3' */
     Text3 = stattext_init(_malloc(sizeof(t_stattext)),
                                r,
                                TX_ALIGN_BOTTOM,
                                INI_TEXT("Style :"));


/* Add the button to the window declared in 'ControlPanel' */
OBJECT(ControlPanel)->insert(OBJECT(ControlPanel), OBJECT(Text3));

/* Declare the history's size in 'r' */
r = rect_assign(72, 100, 192, 120);

/* Declare the history in 'WallStyle' */
 WallStyle = history_init(_malloc(sizeof(t_history)),
                            r,
                            MyVoid_WallStyle() ,
                            150,
                            HF_REWRITEUNABLE|LF_SELFLIST);

/* Add the history to the window declared in 'ControlPanel' */
OBJECT(ControlPanel)->insert(OBJECT(ControlPanel), OBJECT(WallStyle));

if ( WallStyle ) WallStyle->rewrite_item(WallStyle, get_current_style_item());

 };

app_begin ( void ) {

  if ( ap_process == AP_INIT ) { /* When ap start */

      AP_SETNUMOFCALLS(1); /* Set MAX of Calls */

       Show_Win_ControlPanel(); /* Run the init void */

  };

  if ( ap_process == AP_FREE ) {   /*   */

  };
  if ( ap_process == AP_DONE ) {  /* When ap done */

  };
} app_end;

